/*SELECT VERSION(), CURRENT_DATE;*/

USE sql10255392;

/*CREATE TABLE FABRICA(
    ID_FABRICA INT AUTO_INCREMENT,
    PRIMARY KEY (ID_FABRICA),
    NAME VARCHAR(50) NOT NULL UNIQUE
);*/

/*CREATE TABLE PAIS(
    ID_PAIS INT AUTO_INCREMENT,
    PRIMARY KEY (ID_PAIS),
    NAME VARCHAR(50) NOT NULL UNIQUE
);*/

/*CREATE TABLE CERVEZA(
    ID_CERVEZA INT AUTO_INCREMENT,
    PRIMARY KEY (ID_CERVEZA),
    NAME VARCHAR(50) NOT NULL UNIQUE,
    FK_ID_PAIS INT,
    FOREIGN KEY (FK_ID_PAIS) REFERENCES PAIS (ID_PAIS)
);*/
/*
CREATE TABLE CERVEZA_X_FABRICA(
    PFK_CERVEZA INT,
    PFK_FABRICA INT,
    PRIMARY KEY (PFK_CERVEZA, PFK_FABRICA),
    FOREIGN KEY (PFK_CERVEZA) REFERENCES CERVEZA (ID_CERVEZA),
    FOREIGN KEY (PFK_FABRICA) REFERENCES FABRICA (ID_FABRICA)
);*/

SHOW TABLES;
DESCRIBE CERVEZA_X_FABRICA;

