USE sql10255392;

/*CREATE TABLE ESCUELAS(
    ID_ESCUELA INT AUTO_INCREMENT,
    PRIMARY KEY (ID_ESCUELA),
    ESCUELA VARCHAR(50) NOT NULL UNIQUE,
    DIRECCION VARCHAR(50)
);*/

/*CREATE TABLE ESCUELAS_TELEFONOS(
    TELEFONO INT,
    FK_ESCUELA INT,
    PRIMARY KEY (TELEFONO),
    FOREIGN KEY (FK_ESCUELA) REFERENCES ESCUELAS (ID_ESCUELA)
);*/

/*CREATE TABLE RESERVAS(
    ID_RESERVA INT AUTO_INCREMENT,
    FK_ID_ESCUELA INT,
    FECHA INT,
    PRIMARY KEY (ID_RESERVA),
    FOREIGN KEY (FK_ID_ESCUELA) REFERENCES ESCUELAS (ID_ESCUELA)
);*/

/*CREATE TABLE TIPO_VISITA(
    ID_TIPO_VISITA INT AUTO_INCREMENT,
    PRIMARY KEY (ID_TIPO_VISITA),
    TIPO_VISITA VARCHAR(50) NOT NULL UNIQUE,
    ARANCEL INT NOT NULL
);*/

/*CREATE TABLE VISITAS(
    PFK_RESERVA INT,
    PFK_TIPO_VISITA INT,
    GRADO VARCHAR(2) NOT NULL,
    ALUMNOS INT,
    ALUMNOS_REALES INT,
    ARANCEL INT,
    PRIMARY KEY (PFK_RESERVA, PFK_TIPO_VISITA),
    FOREIGN KEY (PFK_RESERVA) REFERENCES RESERVAS (ID_RESERVA),
    FOREIGN KEY (PFK_TIPO_VISITA) REFERENCES TIPO_VISITA (ID_TIPO_VISITA)
);*/

/*CREATE TABLE GUIAS(
    ID_GUIA INT AUTO_INCREMENT,
    PRIMARY KEY (ID_GUIA),
    GUIA VARCHAR(50) NOT NULL UNIQUE
);*/

/*CREATE TABLE VISITAS_GUIAS(
    PFK_RESERVA INT,
    PFK_TIPO_VISITA INT,
    PFK_GUIA INT,
    RESPONSABLE VARCHAR(50),
    PRIMARY KEY (PFK_RESERVA, PFK_TIPO_VISITA, PFK_GUIA),
    FOREIGN KEY (PFK_RESERVA) REFERENCES RESERVAS (ID_RESERVA),
    FOREIGN KEY (PFK_TIPO_VISITA) REFERENCES TIPO_VISITA (ID_TIPO_VISITA),
    FOREIGN KEY (PFK_GUIA) REFERENCES GUIAS (ID_GUIA)
);*/

/*CREATE TABLE LOCALIDADES(
    ID_LOCALIDAD SMALLINT AUTO_INCREMENT,
    PRIMARY KEY (ID_LOCALIDAD),
    LOCALIDAD VARCHAR(50) NOT NULL
);*/

/*ALTER TABLE ESCUELAS
ADD COLUMN FK_ID_LOCALIDAD SMALLINT,
ADD FOREIGN KEY (FK_ID_LOCALIDAD)
REFERENCES LOCALIDADES (ID_LOCALIDAD);*/

/*ALTER TABLE ESCUELAS --BORRAR CLUMNA
DROP COLUMN FK_ID_LOCALIDAD;*/

-- DESCRIBE ESCUELAS;

-- INSERT INTO LOCALIDADES (LOCALIDAD) VALUES ('PINAMAR');
-- INSERT INTO ESCUELAS (ESCUELA, DIRECCION, FK_ID_LOCALIDAD) VALUES ('NOMBRE_ESCUELA7', 'DIRECCION7', 3);
-- INSERT INTO ESCUELAS_TELEFONOS (TELEFONO) VALUES ('26345669');


/*SELECT ESCUELA, DIRECCION, LOC.LOCALIDAD -- MOSTRAR NOMBRE DE LOCALIDADES EN SELECT DE ESCUELAS
FROM ESCUELAS ESC
INNER JOIN LOCALIDADES LOC 
ON ESC.FK_ID_LOCALIDAD = LOC.ID_LOCALIDAD;*/

-- SELECT * FROM ESCUELAS;

SELECT * FROM ESCUELAS_TELEFONOS;

/*UPDATE ESCUELAS_TELEFONOS -- MODIFICAR DATO DE ROW YA EXISTENTE
SET FK_ESCUELA = 2
WHERE TELEFONO = 12345678;*/

/*SELECT LOCALIDAD 
FROM LOCALIDADES
WHERE LOCALIDAD LIKE '%MAR%' --REGULAR EXPRESION JOKERS
ORDER BY LOCALIDAD; --ORDEN ALFABETICO A COLUMNA LOCALIDAD
*/


-- hacer unidad 4 > Consulta y Combinación de tablas -