/*GUIA 1 EJERCICIO 4*/

/*CREATE DATABASE RESTAURANT;*/
/*SHOW DATABASES;*/
USE RESTAURANT;

/*CREATE TABLE DIFICULTADES(
    ID_DIFICULTAD INT AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    PRIMARY KEY (ID_DIFICULTAD)
);*/

/*INSERT INTO DIFICULTADES (NOMBRE)
VALUES ('FACIL'),('INTERMEDIO'),('DIFICIL');*/

/*CREATE TABLE ENCARGADOS(
    ID_ENCARGADO INT AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_ENCARGADO)
);*/

/*INSERT INTO ENCARGADOS (NOMBRE)
VALUES ('JUAN PEREZ'),('COSME FULANITO'),('JHON DOE');*/

/*CREATE TABLE CATEGORIAS(
    ID_CATEGORIA INT AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(300),
    FK_ID_ENCARGADO INT,
    PRIMARY KEY (ID_CATEGORIA),
    FOREIGN KEY (FK_ID_ENCARGADO) REFERENCES ENCARGADOS (ID_ENCARGADO)
);*/

/*INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION, FK_ID_ENCARGADO)
VALUES ('MINUTAS', 'TODO TIPO DE MILANESAS', 1),('ASADO', 'ASADO A LA PARRILA',2),
       ('ENTRADAS', 'ENTRADAS VARIAS',3),('POSTRES','POSTRES',1);*/

/*CREATE TABLE PLATOS(
    ID_PLATO INT AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(300),
    FOTO VARCHAR(100),
    PRECIO DOUBLE,
    FK_ID_DIFICULTAD INT,
    FK_ID_CATEGORIA INT,
    PRIMARY KEY (ID_PLATO),
    FOREIGN KEY (FK_ID_DIFICULTAD) REFERENCES DIFICULTADES (ID_DIFICULTAD),
    FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA)
);*/

/*INSERT INTO PLATOS (NOMBRE, DESCRIPCION, FOTO, PRECIO, FK_ID_DIFICULTAD, FK_ID_CATEGORIA)
VALUES ('MILANESA DE CARNE','MILANESA DE CARNE CON GARNICION','HTTP',110.50,1, 1),
       ('PARRILA LIBRE','PARRILLA CON ACHURAS, ASADO Y VACIO','HTTP',250.30,2,2),
       ('HELADO','HELADO 3 BOCHAS','HTTP',100,1,4);*/

/*CREATE TABLE UNIDADES(
    ID_UNIDAD INT AUTO_INCREMENT,
    NOMBER VARCHAR(50),
    PRIMARY KEY (ID_UNIDAD)
);*/

/*ALTER TABLE UNIDADES DROP COLUMN NOMBER;
ALTER TABLE UNIDADES ADD COLUMN NOMBRE VARCHAR(50) NOT NULL;*/ /*borrar columna mal escrita y agregar not null, 'rename column' funciona tambien segido de modify nombre not null*/

/*DESCRIBE UNIDADES;*/

/*INSERT INTO UNIDADES (NOMBRE)
VALUES ('TAZAS'),('KILOS'),('GRAMOS'),('LITROS'),('MILILITROS'),('UNIDADES');*/

/*CREATE TABLE INGREDIENTES(
    ID_INGREDIENTE INT AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    STOCK INT DEFAULT 0,
    FK_ID_UNIDAD INT,
    PRIMARY KEY (ID_INGREDIENTE),
    FOREIGN KEY (FK_ID_UNIDAD) REFERENCES UNIDADES (ID_UNIDAD)
);*/

/*INSERT INTO INGREDIENTES (NOMBRE, STOCK, FK_ID_UNIDAD)
VALUES ('PECETO',10,2),('PAN RALLADO',11,2),('HUEVO',200,6),('HELADO',50,2);*/

/*CREATE TABLE RECETAS(
    ID_RECETA INT AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    FK_ID_PLATO INT,
    PRIMARY KEY (ID_RECETA),
    FOREIGN KEY (FK_ID_PLATO) REFERENCES PLATOS (ID_PLATO)
);*/

/*INSERT INTO RECETAS (NOMBRE, FK_ID_PLATO)
VALUES ('MILANESA',1),('HELADO',3);*/

/*CREATE TABLE INGREDIENTES_X_RECETA(
    PFK_INGREDIENTE INT,
    PFK_RECETA INT,
    CANTIDAD FLOAT NOT NULL,
    PRIMARY KEY (PFK_INGREDIENTE, PFK_RECETA),
    FOREIGN KEY (PFK_INGREDIENTE) REFERENCES INGREDIENTES (ID_INGREDIENTE),
    FOREIGN KEY (PFK_RECETA) REFERENCES RECETAS (ID_RECETA)
);*/

/*INSERT INTO INGREDIENTES_X_RECETA (PFK_INGREDIENTE,PFK_RECETA,CANTIDAD)
VALUES (1,1,0.3),(2,1,0.1),(3,1,1),(4,2,0.1);*/

/*--MOSTRAR TODOS LOS INGREDIENTES DE LA RECETA DE MILANESA--*/

/*SELECT R.NOMBRE AS 'RECETA', I.NOMBRE AS 'INGREDIENTE', IR.CANTIDAD
FROM RECETAS R
INNER JOIN INGREDIENTES_X_RECETA IR ON R.ID_RECETA = IR.PFK_RECETA
INNER JOIN INGREDIENTES I ON IR.PFK_INGREDIENTE = I.ID_INGREDIENTE
WHERE R.NOMBRE = 'MILANESA';*/

/*--LISTAR PLATOS MONSTRANDO DIFUCULTADES Y CATEGORIAS--*/

/*SELECT P.NOMBRE, P.DESCRIPCION, P.FOTO, P.PRECIO, C.NOMBRE AS 'CATEGORIA', D.NOMBRE AS 'DIFICULTAD', R.NOMBRE AS 'RECETA'
FROM PLATOS P
INNER JOIN CATEGORIAS C ON P.FK_ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN DIFICULTADES D ON P.FK_ID_DIFICULTAD = D.ID_DIFICULTAD
INNER JOIN RECETAS R ON P.ID_PLATO = R.FK_ID_PLATO;*/

/*--CONTAR LA CANTIDAD DE INGREDIENTES PARA LA RECETA MILANESA--*/

/*SELECT COUNT(*)
FROM INGREDIENTES_X_RECETA IR
INNER JOIN RECETAS R ON IR.PFK_RECETA = R.ID_RECETA
WHERE R.NOMBRE = 'MILANESA';*/

/*--CONTAR LA CANTIDAD DE PLATOS POR TIPO DE DIFICULTAD--*/

/*SELECT D.NOMBRE AS 'DIFICULTAD', COUNT(*)
FROM PLATOS P
INNER JOIN DIFICULTADES D ON P.FK_ID_DIFICULTAD = D.ID_DIFICULTAD
GROUP BY FK_ID_DIFICULTAD;*/

/*--LISTAR INGREDIENTES QUE EL STOCK SEA MAYOR A 11 PERO MENOR A 100--*/

/*SELECT *
FROM INGREDIENTES
WHERE STOCK BETWEEN 11 AND 100;*/

/*--LISTAR INGREDIENTES CON MAYOR STOCK--*/

/*SELECT NOMBRE,MAX(STOCK)
FROM INGREDIENTES*/

/*SELECT *
FROM INGREDIENTES
ORDER BY STOCK DESC LIMIT 1;*/ /*Otra forma, que ademas se puede pedir el resto de las columnas*/

